// Default quote collections ported from fortune.nvim
// Source: https://github.com/rubiin/fortune.nvim/blob/master/lua/fortune/lang/en/quotes.lua

export interface Quote {
  text: string;
  author?: string;
}

export const SHORT_QUOTES: Quote[] = [
  { text: "If you don't finish then you're just busy, not productive.", author: "Anonymous" },
  { text: "Talk is cheap. Show me the code.", author: "Linus Torvalds" },
  { text: "In God we trust. All others must bring data.", author: "W. Edwards Deming" },
  { text: "In theory, theory and practice are the same. In practice, they're not.", author: "Yoggi Berra" },
  { text: "Programming is like sex. One mistake and you have to support it for the rest of your life.", author: "Michael Sinz" },
  { text: "A good programmer is someone who always looks both ways before crossing a one-way street.", author: "Doug Linder" },
  { text: "I don't care if it works on your machine! We are not shipping your machine.", author: "Vidiu Platon" },
  { text: "Fix the cause, not the symptom.", author: "Steve Maguire" },
  { text: "It's all talk until the code runs.", author: "Ward Cunningham" },
  { text: "Given enough eyeballs, all bugs are shallow.", author: "Linus Torvalds" },
  { text: "A clever person solves a problem. A wise person avoids it.", author: "Albert Einstein" },
  { text: "Being a good software engineer is 3% talent, 97% not being distracted by the internet.", author: "Unknown" },
  { text: "Any sufficiently advanced technology is indistinguishable from magic.", author: "Arthur C. Clarke" },
  { text: "A ship in port is safe, but that's not what ships are built for.", author: "Grace Hopper" },
  { text: "Never trust a computer you can't throw out a window.", author: "Steve Wozniak" },
  { text: "When in doubt, use brute force.", author: "Ken Thompson" },
  { text: "There is always one more bug to fix.", author: "Ellen Ullman" },
  { text: "If the code and the comments do not match, possibly both are incorrect.", author: "Norm Schryer" },
  { text: "Before software can be reusable it first has to be usable.", author: "Ralph Johnson" },
  { text: "If you optimize everything, you will always be unhappy.", author: "Donald Knuth" },
  { text: "Testing can only prove the presence of bugs, not their absence.", author: "Edsger W. Dijkstra" },
  { text: "The most disastrous thing that you can ever learn is your first programming language.", author: "Alan Kay" },
  { text: "Optimism is an occupational hazard of programming. Feedback is the treatment.", author: "Kent Beck" },
  { text: "I'm not a great programmer. I'm just a good programmer with great habits.", author: "Kent Beck" },
  { text: "One of my most productive days was throwing away 1000 lines of code.", author: "Ken Thompson" },
  { text: "Debugging becomes significantly easier if you first admit that you are the problem.", author: "William Laeder" },
  { text: "Computers are fast; developers keep them slow.", author: "Peter Coffee" },
  { text: "Don't comment bad code - rewrite it.", author: "Brian Kernighan" },
  { text: "The computer was born to solve problems that did not exist before.", author: "Bill Gates" },
  { text: "Make it work, make it right, make it fast.", author: "Kent Beck" },
  { text: "Easy things should be easy and hard things should be possible.", author: "Larry Wall" },
  { text: "Nothing is more permanent than a temporary solution.", author: "Fyodor Dostoevsky" },
  { text: "Software is hard.", author: "Donald Knuth" },
  { text: "They did not know it was impossible, so they did it!", author: "Mark Twain" },
  { text: "To understand recursion, one must first understand recursion.", author: "Stephen Hawking" },
  { text: "Testing leads to failure, and failure leads to understanding.", author: "Burt Rutan" },
  { text: "The best error message is the one that never shows up.", author: "Thomas Fuchs" },
  { text: "Code never lies, comments sometimes do.", author: "Ron Jeffries" },
  { text: "Laziness is a programmer's main virtue.", author: "Larry Wall" },
  { text: "If, at first, you do not succeed, call it version 1.0.", author: "Khayri R.R. Woulfe" },
  { text: "What one programmer can do in one month, two programmers can do in two months.", author: "Fred Brooks" },
  { text: "Truth can only be found in one place: the code.", author: "Robert C. Martin" },
  { text: "Code is like humor. When you have to explain it, it's bad.", author: "Cory House" },
  { text: "Think twice, code once.", author: "Anonymous" },
  { text: "The sooner you start to code, the longer the program will take.", author: "Roy Carlson" },
  { text: "To iterate is human, to recurse divine.", author: "L. Peter Deutsch" },
  { text: "Computers are useless. They can only give you answers.", author: "Pablo Picasso" },
  { text: "Fancy algorithms are slow when n is small, and n is usually small.", author: "Rob Pike" },
  { text: "Caches are bugs waiting to happen.", author: "Rob Pike" },
  { text: "Simplicity does not precede complexity, but follows it.", author: "Alan Perlis" },
  { text: "Optimization hinders evolution.", author: "Alan Perlis" },
  { text: "Experience is the name everyone gives to their mistakes.", author: "Oscar Wilde" },
  { text: "People who are really serious about software should make their own hardware.", author: "Alan Kay" },
  { text: "Software is eating the world, but AI is going to eat software.", author: "Jensen Huang" },
  { text: "People don't care about what you say, they care about what you build.", author: "Mark Zuckerberg" },
  { text: "Controlling complexity is the essence of computer programming.", author: "Brian Kernighan" },
  { text: "The function of good software is to make the complex appear to be simple.", author: "Grady Booch" },
  { text: "First, solve the problem. Then, write the code.", author: "John Johnson" },
  { text: "The best way to predict the future is to invent it.", author: "Alan Kay" },
  { text: "It's not a bug. It's an undocumented feature!", author: "Anonymous" },
  { text: "The only way to go fast is to go well.", author: "Robert C. Martin" },
  { text: "real artists ship.", author: "Steve Jobs" },
];

export const LONG_QUOTES: Quote[] = [
  { text: "Computer science education cannot make anybody an expert programmer any more than studying brushes and pigment can make somebody an expert painter.", author: "Eric S. Raymond" },
  { text: "You can't have great software without a great team, and most software teams behave like dysfunctional families.", author: "Jim McCarthy" },
  { text: "Most good programmers do programming not because they expect to get paid or get adulation by the public, but because it is fun to program.", author: "Linus Torvalds" },
  { text: "Always code as if the guy who ends up maintaining your code will be a violent psychopath who knows where you live.", author: "Martin Golding" },
  { text: "Any fool can write code that a computer can understand. Good programmers write code that humans can understand.", author: "Martin Fowler" },
  { text: "If builders built buildings the way programmers wrote programs, then the first woodpecker that came along would destroy civilization.", author: "Gerald Weinberg" },
  { text: 'Some people, when confronted with a problem, think "I know, I\'ll use regular expressions". Now they have two problems.', author: "Jamie Zawinski" },
  { text: "The first 90% of the code accounts for the first 90% of the development time. The remaining 10% of the code accounts for the other 90% of the development time.", author: "Tom Cargill" },
  { text: "There are only two kinds of languages: the ones people complain about and the ones nobody uses.", author: "Bjarne Stroustrup" },
  { text: "Give someone a program; you frustrate them for a day; teach them how to program, and you frustrate them for a lifetime.", author: "David Leinweber" },
  { text: "If debugging is the process of removing bugs, then programming must be the process of putting them in.", author: "Sam Redwine" },
  { text: "No one in the brief history of computing has ever written a piece of perfect software. It's unlikely that you'll be the first.", author: "Andy Hunt" },
  { text: "Bad programmers worry about the code. Good programmers worry about data structures and their relationships.", author: "Linus Torvalds" },
  { text: "Debugging is twice as hard as writing the code in the first place. Therefore, if you write the code as cleverly as possible, you are, by definition, not smart enough to debug it.", author: "Rajanand" },
  { text: "Everybody in this country should learn to program a computer because it teaches you how to think.", author: "Steve Jobs" },
  { text: "Measuring programming progress by lines of code is like measuring aircraft building progress by weight.", author: "Bill Gates" },
  { text: "In programming, the hard part isn't solving problems but deciding what problems to solve.", author: "Paul Graham" },
  { text: "As a programmer, it is your job to put yourself out of business. What you do today can be automated tomorrow.", author: "Doug McIlroy" },
  { text: "It is far, far easier to make a correct program fast than to make a fast program correct.", author: "Herb Sutter" },
  { text: "Every great developer you know got there by solving problems they were unqualified to solve until they actually did it.", author: "Patrick McKenzie" },
  { text: "C makes it easy to shoot yourself in the foot; C++ makes it harder, but when you do, it blows away your whole leg.", author: "Bjarne Stroustrup" },
  { text: "Programs must be written for people to read, and only incidentally for machines to execute.", author: "Harold Abelson" },
  { text: "There is nothing quite so useless as doing with great efficiency something that should not be done at all.", author: "Peter Drucker" },
  { text: "The computing scientist's main challenge is not to get confused by the complexities of his own making.", author: "Edsger W. Dijkstra" },
  { text: "Unix was not designed to stop its users from doing stupid things, as that would also stop them from doing clever things.", author: "Anonymous" },
  { text: "Perfection is achieved, not when there is nothing more to add, but when there is nothing left to take away.", author: "Anonymous" },
  { text: "For a successful technology, reality must take precedence over public relations, for Nature cannot be fooled.", author: "Richard Feynman" },
  { text: "Care about your craft. Why spend your life developing software unless you care about doing it well?", author: "Anonymous" },
  { text: "DRY - Don't Repeat Yourself. Every piece of knowledge must have a single, unambiguous, authoritative representation within a system.", author: "Anonymous" },
  { text: "Refactor early, refactor often. Just as you might weed and rearrange a garden, rewrite, rework, and re-architect code when it needs it. Fix the root of the problem.", author: "Anonymous" },
  { text: "Test early. Test often. Test automatically. Tests that run with every build are much more effective than test plans that sit on a shelf.", author: "Anonymous" },
  { text: "Don't gather requirements - dig for them. Requirements rarely lie on the surface. They're buried deep beneath layers of assumptions, misconceptions, and politics.", author: "Anonymous" },
];
